# Generated by Django 4.2 on 2023-07-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_websitesettings_about_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='right_image',
            field=models.ImageField(null=True, upload_to='settings/'),
        ),
    ]
