# Generated by Django 4.2 on 2023-07-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_websitesettings_right_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.TextField(),
        ),
    ]
